In [1]:
import os
directory = r'C:\Users\Kacper\Desktop\RO\lab08'
os.chdir(directory)

In [ ]:
import numpy as np
import cv2

eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')


cap = cv2.VideoCapture(0)

while 1:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 5)

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

cap.release()
cv2.destroyAllWindows()

In [57]:
#ZAD 1
import numpy as np
import cv2
import matplotlib.pyplot as plt 
from scipy import ndimage

eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

img1 = cv2.imread('t1.jpg')
img2 = cv2.imread('t2.jpg')


gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
faces1 = face_cascade.detectMultiScale(gray1, 1.11, 5)

gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
faces2 = face_cascade.detectMultiScale(gray2, 1.1, 5)

for (x,y,w,h) in faces1:
        cv2.rectangle(img1,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray1[y:y+h, x:x+w]
        roi_color = img1[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)  
            
for (x,y,w,h) in faces2:
        cv2.rectangle(img2,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray2[y:y+h, x:x+w]
        roi_color = img2[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
cv2.imwrite('zad1O1.jpg', img1)
cv2.imwrite('zad1O2.jpg', img2)

True

In [47]:
#ZAD 2
import numpy as np
import cv2
import matplotlib.pyplot as plt 
from scipy import ndimage

eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

font = cv2.FONT_HERSHEY_SIMPLEX
fontScale = 1
color = (255, 0, 0)
thickness = 2

img1 = cv2.imread('t1.jpg')


gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
faces1 = face_cascade.detectMultiScale(gray1, 1.11, 5)

for (x,y,w,h) in faces1:
        cv2.rectangle(img1,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray1[y:y+h, x:x+w]
        roi_color = img1[y:y+h, x:x+w]
        
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2) 
        pos = (x-20,y-20)
        pos2= "X({x1},{x2}) Y({x3},{x4})".format(x1 = x, x2 = y, x3 = x+w, x4 = y+h)
        img1 = cv2.putText(img1, pos2, pos, font, 
                   fontScale, color, thickness, cv2.LINE_AA)
        
        
            
cv2.imwrite('zad2.jpg', img1)


            

True

In [56]:
import numpy as np
import cv2
import matplotlib.pyplot as plt 
import os

eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

images = []

for filename in os.listdir('dane'):
    img = cv2.imread(os.path.join('dane', filename))
    images.append(img)
    
i = 0
for imga in images:
    gray = cv2.cvtColor(imga, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.5, 5)
    
    print(faces)
    for (x,y,w,h) in faces:
        roi_color = imga[y:y+h, x:x+w]
        cv2.imwrite('faces/o{name}.jpg'.format(name=i), roi_color)
        i+=1
        



[[156 256 615 615]]
[[254 126 410 410]]
[[ 25  64 273 273]
 [336  67 273 273]
 [ 69 105 182 182]
 [383 107 182 182]]


In [54]:
import numpy as np
import cv2
import matplotlib.pyplot as plt 
import os

body_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_fullbody.xml')

img = cv2.imread('t3.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
body = body_cascade.detectMultiScale(gray, 1.1, 5)

for (x,y,w,h) in body:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]

cv2.imwrite('zad4.jpg', img)

True